version: '3.1'
services:
  stats-server:
    build: stats/service
    container_name: stats_container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

#  ewm-service: будет использоваться для основного функционала, пока не используется.
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
